config/routes.rb
Rails.application.routes.draw do
	root :to => 'greetings#index'
  resources :greetings
end

app/models/greetings.rb
class Greetings < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  before_action :get_greeting, only: [:show, :destroy, :edit, :update]

  def get_greeting
    @greeting = Greetings.find(params[:id])
  end

  def return_to_index
    redirect_to :action => 'index', :format => 'html'
  end 


	def show

  end

  def index
  	@greeting = Greetings.all
  end

  def edit

  end

  def update
    @greeting.update!(params[:greetings].permit(:greeting))
    @greeting.save
    return_to_index
  end


  def new
    @greeting = Greetings.new
  end

  def create
    @greeting = Greetings.new(params[:greetings])
    if @greeting.save
      render 'new'
    else
      flash[:notice] = "We failed to create your new greeting."
    end
  end


  def destroy
    @greeting.destroy
    return_to_index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/views/greetings/edit.html.erb
<h1>Edit Greeting in Database</h1>

<div>
	<%= form_for(@greeting) do |f| %>
		<%= f.label :greeting %>
		<%= f.text_field :greeting %>
		<%= f.submit "Update" %>
	<% end %>
</div>

app/views/greetings/index.html.erb
<h1>List All Greetings</h1>
<p><%= link_to 'Create Greeting', greetings_path, method: :new %></p>
<div class='main'>
	<div class='c1'><h2>Index</h2></div>
	<div class='c2'><h2>Description</h2></div>
	<div class='c1'><h2>Change</h2></div>
	<div class='clear'></div>
	<% @greeting.each do |greet| %>
		<div class='c1'><p><%= greet.id %></p></div>
		<div class='c2'><p><%= greet.greeting %></p></div>
		<div class='c1'><p><%= link_to "Edit", edit_greeting_path(greet) %></p></div>
		<div class='c1'><p><%= link_to "Delete", greet, method: :delete %></p></div>
		<div class='clear'></div>
	<% end %>
</div>

app/views/greetings/new.html.erb
<h1>Add a New Greeting to the Database</h1>

	<%= form_for(@greeting) do |f| %>
		<%= f.label :greeting %>
		<%= f.text_field :greeting %>
		<%= f.submit "Submit" %>
	<% end %>

app/views/greetings/show.html.erb
<p><%= @greeting.greeting %></p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Hello World App by Carl Capozza
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", '#', id: "logo" %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Helloapp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>